---
- include: vagrant/ansible/site_ruby.yml

- hosts: [all]
  tasks:
  - name: install gem bundler
    command: /bin/bash -lc "rvm @`cat .ruby-gemset` --create do gem install bundler"
    args:
      chdir: "{{ seek_project_root }}"
  - name: bundle install
    command: /bin/bash -lc "rvm @`cat .ruby-gemset` --create do bundle install"
    args:
      chdir: "{{ seek_project_root }}" 

- hosts: [mysql]
  roles:
    - role: geerlingguy.mysql
      become: yes

- hosts: [all]
  tasks:
    - name: bundle install
      command: /bin/bash -lc "cd {{ seek_project_root }} && bundle install"
    - name: generate config files from templates
      template:
        src:  "{{ seek_project_root }}/{{ item }}.tpl"
        dest: "{{ seek_project_root }}/{{ item }}"
      with_items:
        - "config/database.yml"
        - "config/sunspot.yml"
    - name: rake db:migrate
      command: /bin/bash -lc "cd {{ seek_project_root }} && rake db:migrate RAILS_ENV={{ rails_env }}"
    - name: copy initd scripts for services
      become: yes
      template:
        src:  "{{ seek_project_root }}/script/initd/{{ item }}.tpl"
        dest: "/etc/init.d/{{ item }}"
        mode: 0751
      with_items: "{{ seek_initd }}"
    - name: enable and start services
      become: yes
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items: "{{ seek_initd }}"
    - name: add RAILS_ENV in shell profile
      lineinfile:
        dest:        "{{ ansible_env.HOME }}/.profile"
        backup:      yes
        state:       present
        line:        'export RAILS_ENV={{ rails_env }}'
        regexp:      '^export RAILS_ENV=.*$'

- hosts: [nginx]
  roles:
    - role: geerlingguy.nginx
      become: yes

- hosts: [passenger]
  roles:
    - role: geerlingguy.passenger
      become: yes
  tasks:
    - name: Ensure passenger virtual host is disabled until the geerlingguy.passenger supports better configuration
      become: yes
      file:
        dest: /etc/nginx/sites-enabled/passenger
        state: absent
