production:
  solr:
    hostname: localhost
    port: 8904
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8905
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    
